### ISSUE TITLE
String in div or view tags generate unwanted styles

### ISSUE THREAD

**Issue by zguolee** [unocss-applet/unocss-applet#2]
```html
<div>
  py-4.5
</div>
```
generate
```css
.py-4\\\\.5{
  padding-top:1.125rem;
  padding-bottom:1.125rem;
}
```
We don’t need the style of this selector, and change the name directly
