### ISSUE TITLE
bug: 开发与打包编译不一致

### ISSUE THREAD

**Issue by yang1206** [unocss-applet/unocss-applet#26]
https://github.com/MoomFE/unocss-preset-extra
使用这个预设插件，开发与打包编译结果不一致

开发为
```css
[size~="\32320"] {
  width: 10px;
  height: 10px;
}
```

build后为
```css
[size~=\32320] {
  width: 10px;
  height: 10px
}
```

![](https://s2.loli.net/2023/06/16/rJO2ZcGmnq3spDV.png)
