### ISSUE TITLE
使用 `divide` 多出描边

### ISSUE THREAD

**Issue by sgbke** [unocss-applet/unocss-applet#28]
使用这样写法会在左右多出描边
``` html
  <view class="px-4 divide-y divide-red divide-solid">
    <view v-for="v in 10" :key="v" class="py-2">
      <view class="h-10 w-10 bg-amber" />
    </view>
  </view>
```
![image](https://github.com/unocss-applet/unocss-applet/assets/31548433/473be60a-17a9-4404-90a0-bcf8ad08aab7)

删除 `divide-solid` 样式，手动添加样式，可以正常显示。
``` css
.divide-y>view+view,
.divide-y>button+button,
.divide-y>text+text,
.divide-y>image+image {
  border-top-style: solid;
  border-bottom-style:solid;
}
```

**Comment by zguolee** [comment]
我试了一下，这种情况是正常的，[UnoCSS](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCJwTCApgWgE98AWKLHAgJ1xHMkvxGQAtaoAXXADw-xlwA7LlSgAHfAGZ0APgBQUKKEgyAjMAD0WeYuUQZAJk3aFS7ZOMq5l-XKA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUACLBaE3gDd6aqJu279ANXXtNMAOJQIXMJQC%2BcLB4gcADkXCoSdHTBSEgYAB6QsOjY6lwANvCYOPhEJMCkABTIqFDp9ABccADaVKhVwRJcdDAQIAC0pWkYweSIcFJp0JXBtGjBcD4AulSTsnQAFtAwjTB0lcWoIY3NrW0LSyvBwzDxMG1ppHAncWfQmqQYcIsWUOXXZyfqadGoPrIiCjW1VqclEShUBQAlLJhPJGCw2JweHx%2BFCYaCFJJpEUQag6BIvhhKgBGAB0ACZ0agJGhcMN5qwwGsAPTM%2BggUkLZk-TY%2BaEzKw2HRQPRQIFVDRaYWiowmcz0NFXaxSuxQRzOXBuDxeKGzJB8pBAA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g) 也是这样，需要有一个 reset：
```css
*,:before,:after {
    box-sizing: border-box;
    border-width: 0;
    border-style: solid;
    border-color: #e5e7eb
}
```
或许我们也可以写一个小程序版本的 [reset](https://github.com/unocss/unocss/blob/main/packages/reset/tailwind.css)，PR Welcome!
